/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as BodekasseRouteImport } from './routes/bodekasse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FixturesIndexRouteImport } from './routes/fixtures.index'
import { Route as FixturesFixtureIdRouteImport } from './routes/fixtures.$fixtureId'

const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const BodekasseRoute = BodekasseRouteImport.update({
  id: '/bodekasse',
  path: '/bodekasse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesIndexRoute = FixturesIndexRouteImport.update({
  id: '/fixtures/',
  path: '/fixtures/',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesFixtureIdRoute = FixturesFixtureIdRouteImport.update({
  id: '/fixtures/$fixtureId',
  path: '/fixtures/$fixtureId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bodekasse': typeof BodekasseRoute
  '/squad': typeof SquadRoute
  '/upcoming': typeof UpcomingRoute
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRoute
  '/fixtures/': typeof FixturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bodekasse': typeof BodekasseRoute
  '/squad': typeof SquadRoute
  '/upcoming': typeof UpcomingRoute
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRoute
  '/fixtures': typeof FixturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bodekasse': typeof BodekasseRoute
  '/squad': typeof SquadRoute
  '/upcoming': typeof UpcomingRoute
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRoute
  '/fixtures/': typeof FixturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bodekasse'
    | '/squad'
    | '/upcoming'
    | '/fixtures/$fixtureId'
    | '/fixtures/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bodekasse'
    | '/squad'
    | '/upcoming'
    | '/fixtures/$fixtureId'
    | '/fixtures'
  id:
    | '__root__'
    | '/'
    | '/bodekasse'
    | '/squad'
    | '/upcoming'
    | '/fixtures/$fixtureId'
    | '/fixtures/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BodekasseRoute: typeof BodekasseRoute
  SquadRoute: typeof SquadRoute
  UpcomingRoute: typeof UpcomingRoute
  FixturesFixtureIdRoute: typeof FixturesFixtureIdRoute
  FixturesIndexRoute: typeof FixturesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bodekasse': {
      id: '/bodekasse'
      path: '/bodekasse'
      fullPath: '/bodekasse'
      preLoaderRoute: typeof BodekasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures/': {
      id: '/fixtures/'
      path: '/fixtures'
      fullPath: '/fixtures/'
      preLoaderRoute: typeof FixturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures/$fixtureId': {
      id: '/fixtures/$fixtureId'
      path: '/fixtures/$fixtureId'
      fullPath: '/fixtures/$fixtureId'
      preLoaderRoute: typeof FixturesFixtureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BodekasseRoute: BodekasseRoute,
  SquadRoute: SquadRoute,
  UpcomingRoute: UpcomingRoute,
  FixturesFixtureIdRoute: FixturesFixtureIdRoute,
  FixturesIndexRoute: FixturesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
