/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as BodekasseRouteImport } from './routes/bodekasse'
import { Route as IndexRouteImport } from './routes/index'

const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const BodekasseRoute = BodekasseRouteImport.update({
  id: '/bodekasse',
  path: '/bodekasse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bodekasse': typeof BodekasseRoute
  '/squad': typeof SquadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bodekasse': typeof BodekasseRoute
  '/squad': typeof SquadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bodekasse': typeof BodekasseRoute
  '/squad': typeof SquadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bodekasse' | '/squad'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bodekasse' | '/squad'
  id: '__root__' | '/' | '/bodekasse' | '/squad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BodekasseRoute: typeof BodekasseRoute
  SquadRoute: typeof SquadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bodekasse': {
      id: '/bodekasse'
      path: '/bodekasse'
      fullPath: '/bodekasse'
      preLoaderRoute: typeof BodekasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BodekasseRoute: BodekasseRoute,
  SquadRoute: SquadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
